apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cat
  namespace: default
spec:
  ingressClassName: nginx
  defaultBackend:
    resource:
      apiGroup: animals.example.com
      kind: StorageBucket
      name: static-assets
  rules:
  - host: animals.example.com
    http:
      paths:
      - path: /cat
        pathType: Prefix
        backend: 
          service:
            name: nginx-cat-svc
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cat-svc
  labels:
    app: nginx-cat-svc
spec:
#  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
#    nodePort: 30010
  selector:
    app: nginx-cat-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cat-test
spec:
  selector:
    matchLabels:
      app: nginx-cat-test
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-cat-test
    spec:
      volumes:
      - name: nginx-cat-html
        configMap:
          name: nginx-cat-html
      containers:
      - name: nginx-cat-test
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/cat
          name: nginx-cat-html
          readOnly: true
        ports:
        - containerPort: 8080
#        securityContext:
#          privileged: true
